apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-api-config
  namespace: orders-prod

data:
  APP_NAME: "orders-api"
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"

  DB_HOST: "orders-db.postgres.database.azure.com"
  DB_PORT: "5432"
  DB_NAME: "orders"

  DB_SSL_MODE: "require"
