apiVersion: v1
kind: ResourceQuota

metadata:
  name: orders-api-quota
  namespace: orders-prod

spec:

  hard:

    requests.cpu: "8"
    requests.memory: 16Gi

    limits.cpu: "16"
    limits.memory: 32Gi

    pods: "30"

    services: "10"

    configmaps: "20"

    secrets: "20"
