apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: orders-api-kv
  namespace: orders-prod

spec:
  provider: azure

  parameters:
    usePodIdentity: "false"

    clientID: "<UAMI-CLIENT-ID>"

    keyvaultName: "orders-prod-kv"

    tenantId: "<TENANT-ID>"

    objects: |
      array:
        - |
          objectName: DB_USERNAME
          objectType: secret
          objectVersion: ""

        - |
          objectName: DB_PASSWORD
          objectType: secret
          objectVersion: ""

        - |
          objectName: API_KEY
          objectType: secret
          objectVersion: ""
